from datetime import datetime

NUM_LEARNERS = 150
BASE_PATH = "data_source"

# Set random seed for reproducibility
RANDOM_SEED = 42

# Program details
COHORTS = ["Cohort-A", "Cohort-B", "Cohort-C", "Cohort-D"]
TRACKS = ["Power BI Track", "AWS Cloud Track"]
START_DATE = datetime(2025, 1, 1)
NUM_WEEKS = 12
DAYS_PER_WEEK = 5

# Names for realistic data
FIRST_NAMES = [
    "John",
    "Jane",
    "Michael",
    "Sarah",
    "David",
    "Emily",
    "Robert",
    "Jessica",
    "William",
    "Jennifer",
    "James",
    "Linda",
    "Richard",
    "Patricia",
    "Joseph",
    "Mary",
    "Thomas",
    "Elizabeth",
    "Charles",
    "Barbara",
    "Daniel",
    "Susan",
    "Matthew",
    "Nancy",
    "Anthony",
    "Margaret",
    "Mark",
    "Karen",
    "Donald",
    "Lisa",
    "Steven",
    "Betty",
    "Paul",
    "Dorothy",
    "Andrew",
    "Sandra",
    "Joshua",
    "Ashley",
    "Kenneth",
    "Kimberly",
    "Kevin",
    "Donna",
    "Brian",
    "Emily",
    "George",
    "Carol",
    "Edward",
    "Michelle",
    "Ronald",
    "Amanda",
    "Timothy",
    "Melissa",
    "Jason",
    "Deborah",
]

LAST_NAMES = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
]
